[project]
name = "learning-genai"
version = "0.1.0"
description = "brushing up on advanced python and learning generative ai "
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.12.5",
]
